### ISSUE TITLE
Always returns invalid

### ISSUE THREAD

**Issue by alexrabin** [kkazuo/ssl-checker#1]
```dart
final result = await sslChecker('https://www.google.com');
print(result)
```

Always returns false.

**Comment by kkazuo** [comment]
oh! Thank you for your report.
I'll check it out.

**Comment by kkazuo** [comment]
@alexrabin Hi, thank you for reports.

This is not a bug, this is the design.
You must pass the hostname, not URI.

```dart
final result = await sslChecker('www.google.com');
```

Thank you,
